/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "FreeRTOS.h"
#include "task.h"
#include "FreeRTOSConfig.h"
#include "led.h"


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void AperiodicRED_LED(void *pmParam)
{
	while(1)
	{
		LedBlink(LED_RED, 1000);
		vTaskDelay(1000/portTICK_RATE_MS);

	}
	vTaskDelete(NULL);
}
void AperiodicGREEN_LED(void *pmParam)
{
	while(1)
	{
		LedBlink(LED_GREEN, 2000);
		vTaskDelay(1000/portTICK_RATE_MS);

	}
	vTaskDelete(NULL);
}
void AperiodicBLUE_LED(void *pmParam)
{
	while(1)
	{
		LedBlink(LED_BLUE, 3000);
		vTaskDelay(1000/portTICK_RATE_MS);

	}
	vTaskDelete(NULL);
}
void AperiodicORANGE_LED(void *pmParam)
{
	while(1)
	{
		LedBlink(LED_ORANGE, 4000);
		vTaskDelay(1000/portTICK_RATE_MS);

	}
	vTaskDelete(NULL);
}
int main()
{
	LedInit(LED_GREEN);
	LedInit(LED_ORANGE);
	LedInit(LED_RED);
	LedInit(LED_BLUE);
	xTaskCreate(AperiodicRED_LED,"red_led",configMINIMAL_STACK_SIZE,NULL,2,NULL);
	xTaskCreate(AperiodicGREEN_LED,"green_led",configMINIMAL_STACK_SIZE,NULL,2,NULL);
	xTaskCreate(AperiodicBLUE_LED,"blue_led",configMINIMAL_STACK_SIZE,NULL,2,NULL);
	xTaskCreate(AperiodicORANGE_LED,"orange_led",configMINIMAL_STACK_SIZE,NULL,2,NULL);


	vTaskStartScheduler();
	while(1);

	return 0;
}





